### ISSUE TITLE
Casing of column names in query generates "insufficient column mapping"

### ISSUE THREAD

**Issue by phillipCouto** [relops/cqlr#1]
When I bind to a query that has casing to the column names I get the error mentioned above. If I remove the casing from the column names in the query it works correctly.

Is that by design?

I thought cassandra is case insensitive.

**Comment by 0x6e6562** [comment]
Could you paste an example of the scenario that causes this issue?

**Comment by phillipCouto** [comment]
Created pull request #2 to illustrate the issue :)

**Comment by phillipCouto** [comment]
Resolved by PR #3 .
