### ISSUE TITLE
Casing of column names in query generates "insufficient column mapping"

### ISSUE THREAD

**Issue by jared-mackey** [relops/cqlr#10]
This is a repost of #1 because I am still experiencing a similar issue. Shouldn't it be case insensitive? Or could we give it a better error message? This was really confusing and started looking all over the C\* table and looking over my code for other mistakes.

This is broken

``` go
type testModel struct {
    uuid   gocql.UUID
    value1 string
    value2 int
}
```

But this one works. 

``` go
type testModel struct {
    Uuid   gocql.UUID
    Value1 string
    Value2 int
}
```

**Comment by 0x6e6562** [comment]
Thanks for pointing this issue out - you are right, the library should be more explicit with error messages to prevent people from wasting time chasing down confusing error messages - we should get around to fixing this.
